/* applet.c generated by valac, the Vala compiler
 * generated from applet.vala, do not modify */

/*
 * A simple applet written in Vala that shows a stock icon.
 *
 * Copyright (C) 2007, 2008, 2009 Mark Lee <avant-wn@lazymalevolence.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Author : Mark Lee <avant-wn@lazymalevolence.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <libawn/libawn.h>
#include <stdlib.h>
#include <string.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



AwnApplet* awn_applet_factory_initp (const char* canonical_name, const char* uid, gint panel_id);



AwnApplet* awn_applet_factory_initp (const char* canonical_name, const char* uid, gint panel_id) {
	AwnApplet* result = NULL;
	AwnAppletSimple* applet;
	AwnAppletSimple* _tmp0_;
	g_return_val_if_fail (canonical_name != NULL, NULL);
	g_return_val_if_fail (uid != NULL, NULL);
	applet = NULL;
	applet = (_tmp0_ = g_object_ref_sink ((AwnAppletSimple*) awn_applet_simple_new (canonical_name, uid, panel_id)), _g_object_unref0 (applet), _tmp0_);
	awn_applet_simple_set_icon_name (applet, "gtk-yes");
	result = (AwnApplet*) applet;
	return result;
}




