#
# Places
#
usr/lib/awn/applets/places/*.so 
usr/share/avant-window-navigator/applets/places.desktop 
usr/share/avant-window-navigator/schemas/awn-applet-places.schema-ini
etc/gconf/schemas/awn-applet-places.schemas

usr/lib/awn/applets/trasher/*.so
usr/lib/awn/applets/filebrowser/*.so
usr/lib/awn/applets/main-menu/*.so
usr/lib/awn/applets/webapplet/*.so
usr/share/avant-window-navigator/applets/trasher.desktop
usr/share/avant-window-navigator/applets/filebrowser.desktop
usr/share/avant-window-navigator/applets/main-menu.desktop
usr/share/avant-window-navigator/applets/webapplet.desktop
usr/share/icons/hicolor/scalable/apps/filebrowser.svg
etc/gconf/schemas/filebrowser.schemas
etc/gconf/schemas/webapplet.schemas
